### ISSUE TITLE
Support Plasma 6 (Port to KF6)

### ISSUE THREAD

**Issue by DarkXero-dev** [HimDek/Overview-Widget-for-Plasma#1]
Please port this widget to KDE Framework 6. The guidelines are [here](https://develop.kde.org/docs/plasma/widget/porting_kf6/).

**Comment by HimDek** [comment]
Thanks for the reminder. Will look into it.

**Comment by HimDek** [comment]
Completed https://github.com/HimDek/Overview-Widget-for-Plasma/commit/9a463a79244c24edbbcd1910ee27fc98ebdcd425 and released: https://store.kde.org/p/2132554
