### ISSUE TITLE
plasma 6 widget doesnt work

### ISSUE THREAD

**Issue by claudemods** [HimDek/Overview-Widget-for-Plasma#2]
hello mate i know its early days and plasma 6.0 has only just been released but i want to make you aware that your widget doesnt work on the new kde neon

**Comment by CosmicBagel** [comment]
I'm on Arch running Plasma 6.0.2, the widget doesn't work.

Changing `qdbus` to `qdbus6` in the `contents/config/main.xml` line 15 fixes it

```xml
    <entry name="command" type="String">
      <label>Command to execute</label>
      <default>qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut Overview</default>
    </entry>
```

Not sure if this will also work on KDE Neon, as far as I know this will not work at all with Plasma 5 (QT5 vs QT6 differences)

**Comment by HimDek** [comment]
> I'm on Arch running Plasma 6.0.2, the widget doesn't work.
> 
> Changing `qdbus` to `qdbus6` in the `contents/config/main.xml` line 15 fixes it
> 
> ```
>     <entry name="command" type="String">
>       <label>Command to execute</label>
>       <default>qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut Overview</default>
>     </entry>
> ```
> 
> Not sure if this will also work on KDE Neon, as far as I know this will not work at all with Plasma 5 (QT5 vs QT6 differences)

Thanks for the information. While `qdbus` should idealy work for both plasma 5 and 6, some distributions or systems may have different packages installed. For the plasma 6 branch, I will update it to use `qdbus6` as soon as possible.

**Comment by HimDek** [comment]
Fixed in https://github.com/HimDek/Overview-Widget-for-Plasma/commit/6bf6f50578034c170f6782cde1cab6a208eac0d6

**Comment by HimDek** [comment]
Will release update soon.
