### ISSUE TITLE
Overview Shortcut on KDE 6 Panel does not invoke/toggle Overview action

### ISSUE THREAD

**Issue by RobotCosmonaut** [HimDek/Overview-Widget-for-Plasma#6]
Problem Environment: 
KDE Plasma Fedora 40
Overview installed via Fedora Discover on 2024-04-27

Problem Description:
Attempts to invoke/toggle via the  mouse clickable shortcut added to the panel in KDE Plasma Fedora 40 does not yield any results. Inspection yields that Overview is enabled in the System Desktop Effects Settings. 

Conversely, selecting the Meta-W shortcut does invoke Overview thus this appears limited to not being able to be invoked via the panel shortcut.

Steps to Reproduce:
1) Install Overview via the Discover application in KDE Plasma Fedora 40
2) Add Overview shortcut to panel
3) Attempt to invoke Overview via the panel shortcut
Result: Overview application is not invoke via panel despite being enabled via System Desktop Effects Settings

Operational Impact:
Overview not able to be toggled via the panel shortcut

Workaround:
Invoke Overview via the Meta-W hotkey combination

**Comment by HimDek** [comment]
I hope you have enabled Overview Effect in Plasma settings. If it still does not work, see #3.

**Comment by tyvsmith** [comment]
Same situation for me. On a Fedora 40 Kinoite image under X11 and Plasma 6.0.4.  Ctrl-w works fine, icon doesn't. What's noted in #3 about clicking and holding and dragging off does not have any impact.

**Comment by HimDek** [comment]
Executing the below command and check if it invokes the overview.
``` bash
qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut Overview
```

**Comment by RobotCosmonaut** [comment]
Entering the following via bash-Konsole:

`qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut Overview`

yields the following:

> bash: qdbus6: command not found...
> Similar command is: 'qdbus'

Subsequently changing the command to following:

` qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview`
 
Successfully yields the invoke of Overview

**Comment by HimDek** [comment]
> Entering the following via bash-Konsole:
> 
> `qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut Overview`
> 
> yields the following:
> 
> > bash: qdbus6: command not found...
> > Similar command is: 'qdbus'
> 
> Subsequently changing the command to following:
> 
> ` qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview`
>  
> Successfully yields the invoke of Overview 
> 

Are you using Plasma 5? qdbus6 should be available on Plasma 6.

**Comment by HimDek** [comment]
Ok, so in my system in Plasma 6 on Arch Linux qdbus6 is actually a symlink to qdbus. Other distributions may or may not have qdbus6 as a symlink to qdbus. However using qdbus instead of qdbus6 should work in all systems. Working on it now.

But I am concerned about some distributions having qdbus6 but not qdbus. I hope that does not happen.

**Comment by HimDek** [comment]
Fixed with 500735e.

**Comment by tyvsmith** [comment]
On my system the following two binaries exist:
/usr/bin/qdbus-qt6
/usr/bin/qdbus

Both work with the command. If I symlink those to qdbus6, then the widget works BUT it requires holding the mouse button down. If I release it, it stops, which looks like #3 

> But I am concerned about some distributions having qdbus6 but not qdbus. I hope that does not happen.

Why not put a shell script in the project that checks it's exists, falls back between multiple binaries, or logs the missing one?

**Comment by HimDek** [comment]
> Why not put a shell script in the project that checks it's exists, falls back between multiple binaries, or logs the missing one?

Can be done. For now using qdbus. Hopefuly, it should work everywhere.
